version: "3.9"
   
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: bash -c "
        pipenv run python manage.py migrate
        && pipenv run python manage.py runserver 0.0.0.0:8000
        "
    volumes:
      - ./backend/:/usr/src/cod/
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: